#!/bin/sh

# Enables spdlog garded with DRAKE_LOGGER_DEBUG() and  DRAKE_LOGGER_TRACE():
# For specific files, add copts = ["-UNDEBUG"], in the BUILD.bazel file.
#bazel run --copt -UNDEBUG pile_of_objects -- \
bazel run pile_of_objects -- \
`#General` \
--simulation_time=2 \
--simulator_publish_every_time_step=0 \
--mbp_time_step=1.0e-3 \
--objects_per_pile=3 \
`# Visualization` \
--simulator_target_realtime_rate=0 \
--visualize=1 \
--viz_period=0.016 \
--tamsi=1 \
`#Integration: ` \
`#  bogacki_shampine3` \
`#  explicit_euler,semi_explicit_euler` \
`#  implicit_euler,velocity_implicit_euler` \
`#  radau1,radau3` \
`#  runge_kutta2,runge_kutta3,runge_kutta5` \
--simulator_integration_scheme=implicit_euler \
--simulator_max_time_step=0.01 \
--simulator_accuracy=1.0e-2 \
--jacobian_scheme=forward \
--fixed_step=0 \
--use_full_newton=0 \
--h_loose_band=0 \
--a_loose_band=0.5 \
`#Contact parameters` \
--penetration_allowance=1e-4 \
--stiction_tolerance=1e-4 \
--friction_coefficient=1.0 \
`#Collision geometry type:` \
--only_collision_spheres=1 \
--num_spheres=3 \
`#SPDlog: debug, trace, warn,unchanged (default)` \
--spdlog_level=unchanged
