load("//tools/lint:lint.bzl", "add_lint_tests")
load(
    "//tools/skylark:drake_cc.bzl",
    "drake_cc_googletest",
    "drake_cc_library",
    "drake_cc_package_library",
)

package(
    default_visibility = ["//visibility:public"],
)

drake_cc_package_library(
    name = "fast_sap",
    visibility = ["//visibility:public"],
    deps = [
        ":eigen_pool",
        ":constraint_data",
    ],
)

drake_cc_library(
    name = "constraint_data",
    hdrs = ["constraint_data.h"],
    deps = [
        "//common:essential",
        ":eigen_pool",
    ],
)

drake_cc_library(
    name = "eigen_pool",
    hdrs = ["eigen_pool.h"],
    deps = [
        "//common:essential",
    ],
)

drake_cc_library(
    name = "model_size",
    hdrs = ["model_size.h"],
    deps = [
        "//common:essential",
    ],
)

drake_cc_library(
    name = "patch_constraint_data",
    hdrs = ["patch_constraint_data.h"],
    deps = [
        "//common:essential",
        ":eigen_pool",
    ],
)

drake_cc_googletest(
    name = "eigen_pool_test",
    deps = [
        ":eigen_pool",
        "//common/test_utilities:expect_throws_message",
    ],
)

drake_cc_googletest(
    name = "constraint_data_test",
    deps = [
        ":constraint_data",
        "//common/test_utilities:expect_throws_message",
    ],
)

drake_cc_googletest(
    name = "patch_constraint_data_test",
    deps = [
        ":patch_constraint_data",
        "//common/test_utilities:expect_throws_message",
    ],
)

drake_cc_googletest(
    name = "model_size_test",
    deps = [
        ":model_size",
    ],
)

drake_cc_googletest(
    name = "two_spheres_test",
    deps = [
        "//common/test_utilities:eigen_matrix_compare",
        "//multibody/parsing:parser",
        "//systems/framework:diagram_builder",
    ],
)


add_lint_tests()
